version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wordpress_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:fpm
    container_name: wordpress_app
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - wordpress_network

  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network

volumes:
  mysql_data:
  wordpress_data:

networks:
  wordpress_network:
    name: wordpress_network
